create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/blk_mem_gen_0/doutb[0]} {design_1_i/blk_mem_gen_0/doutb[1]} {design_1_i/blk_mem_gen_0/doutb[2]} {design_1_i/blk_mem_gen_0/doutb[3]} {design_1_i/blk_mem_gen_0/doutb[4]} {design_1_i/blk_mem_gen_0/doutb[5]} {design_1_i/blk_mem_gen_0/doutb[6]} {design_1_i/blk_mem_gen_0/doutb[7]} {design_1_i/blk_mem_gen_0/doutb[8]} {design_1_i/blk_mem_gen_0/doutb[9]} {design_1_i/blk_mem_gen_0/doutb[10]} {design_1_i/blk_mem_gen_0/doutb[11]} {design_1_i/blk_mem_gen_0/doutb[12]} {design_1_i/blk_mem_gen_0/doutb[13]} {design_1_i/blk_mem_gen_0/doutb[14]} {design_1_i/blk_mem_gen_0/doutb[15]} {design_1_i/blk_mem_gen_0/doutb[16]} {design_1_i/blk_mem_gen_0/doutb[17]} {design_1_i/blk_mem_gen_0/doutb[18]} {design_1_i/blk_mem_gen_0/doutb[19]} {design_1_i/blk_mem_gen_0/doutb[20]} {design_1_i/blk_mem_gen_0/doutb[21]} {design_1_i/blk_mem_gen_0/doutb[22]} {design_1_i/blk_mem_gen_0/doutb[23]} {design_1_i/blk_mem_gen_0/doutb[24]} {design_1_i/blk_mem_gen_0/doutb[25]} {design_1_i/blk_mem_gen_0/doutb[26]} {design_1_i/blk_mem_gen_0/doutb[27]} {design_1_i/blk_mem_gen_0/doutb[28]} {design_1_i/blk_mem_gen_0/doutb[29]} {design_1_i/blk_mem_gen_0/doutb[30]} {design_1_i/blk_mem_gen_0/doutb[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/blk_mem_gen_0/addrb[0]} {design_1_i/blk_mem_gen_0/addrb[1]} {design_1_i/blk_mem_gen_0/addrb[2]} {design_1_i/blk_mem_gen_0/addrb[3]} {design_1_i/blk_mem_gen_0/addrb[4]} {design_1_i/blk_mem_gen_0/addrb[5]} {design_1_i/blk_mem_gen_0/addrb[6]} {design_1_i/blk_mem_gen_0/addrb[7]} {design_1_i/blk_mem_gen_0/addrb[8]} {design_1_i/blk_mem_gen_0/addrb[9]} {design_1_i/blk_mem_gen_0/addrb[10]} {design_1_i/blk_mem_gen_0/addrb[11]} {design_1_i/blk_mem_gen_0/addrb[12]} {design_1_i/blk_mem_gen_0/addrb[13]} {design_1_i/blk_mem_gen_0/addrb[14]} {design_1_i/blk_mem_gen_0/addrb[15]} {design_1_i/blk_mem_gen_0/addrb[16]} {design_1_i/blk_mem_gen_0/addrb[17]} {design_1_i/blk_mem_gen_0/addrb[18]} {design_1_i/blk_mem_gen_0/addrb[19]} {design_1_i/blk_mem_gen_0/addrb[20]} {design_1_i/blk_mem_gen_0/addrb[21]} {design_1_i/blk_mem_gen_0/addrb[22]} {design_1_i/blk_mem_gen_0/addrb[23]} {design_1_i/blk_mem_gen_0/addrb[24]} {design_1_i/blk_mem_gen_0/addrb[25]} {design_1_i/blk_mem_gen_0/addrb[26]} {design_1_i/blk_mem_gen_0/addrb[27]} {design_1_i/blk_mem_gen_0/addrb[28]} {design_1_i/blk_mem_gen_0/addrb[29]} {design_1_i/blk_mem_gen_0/addrb[30]} {design_1_i/blk_mem_gen_0/addrb[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/blk_mem_gen_0/enb]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
